/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20KGL } from "./ERC20KGL";
export type { GaugeController } from "./GaugeController";
export type { Registry } from "./Registry";
export type { VotingEscrow } from "./VotingEscrow";
export type { ERC20 } from "./ERC20";
export type { Multicall } from "./Multicall";

export { ERC20KGL__factory } from "./factories/ERC20KGL__factory";
export { GaugeController__factory } from "./factories/GaugeController__factory";
export { Registry__factory } from "./factories/Registry__factory";
export { VotingEscrow__factory } from "./factories/VotingEscrow__factory";
export { ERC20__factory } from "./factories/ERC20__factory";
export { Multicall__factory } from "./factories/Multicall__factory";
