/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20KGL } from "./ERC20KGL";
export type { VotingEscrow } from "./VotingEscrow";

export { ERC20KGL__factory } from "./factories/ERC20KGL__factory";
export { VotingEscrow__factory } from "./factories/VotingEscrow__factory";
