/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VotingEscrow } from "./VotingEscrow";

export { VotingEscrow__factory } from "./factories/VotingEscrow__factory";
